# Generated by Django 5.0.5 on 2024-05-08 01:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(help_text='City or location for the forecast', max_length=255)),
                ('pm1', models.FloatField(blank=True, help_text='Projected PM1 value', null=True)),
                ('pm25', models.FloatField(blank=True, help_text='Projected PM2.5 value', null=True)),
                ('pm10', models.FloatField(blank=True, help_text='Projected PM10 value', null=True)),
                ('no2', models.FloatField(blank=True, help_text='Projected NO2 value', null=True)),
                ('aqi', models.FloatField(help_text='Projected overall AQI value')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the forecast was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the forecast was last updated')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
