# Generated by Django 5.0.5 on 2024-05-07 20:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AQReadings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(max_length=8)),
                ('longitude', models.FloatField(max_length=8)),
                ('pm1', models.FloatField(blank=True, max_length=5, null=True)),
                ('pm25', models.FloatField(blank=True, max_length=5, null=True)),
                ('pm10', models.FloatField(blank=True, max_length=5, null=True)),
                ('no2', models.FloatField(blank=True, max_length=5, null=True)),
                ('humidity', models.FloatField()),
                ('temperature', models.FloatField(blank=True, max_length=5, null=True)),
                ('overallAQI', models.FloatField()),
                ('recordTime', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
