# Generated by Django 5.0.5 on 2024-05-08 01:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aqmonitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aqreadings',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=datetime.date.today),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aqreadings',
            name='recordTime',
            field=models.DateTimeField(),
        ),
    ]
